version: "3.7"

services:
  postgres:
    image: postgres:12.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - mossu-postgres:/var/lib/postgresql/data

  redis:
    image: redis:6.0.9
    ports:
      - 6379:6379
    volumes:
      - mossu-redis:/var/lib/redis/data

volumes:
  mossu-postgres:
  mossu-redis: