version: "3.7"

services:
  postgres:
    image: postgres:12.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - mossu-postgres:/var/lib/postgresql/data

  redis:
    image: redis:6.0.9
    volumes:
      - mossu-redis:/var/lib/redis/data
  
  mossu:
    build: .
    depends_on:
      - postgres
      - redis
    volumes:
      - type: bind
        source: ./
        target: /opt/app/mossu
    ports:
      - '3001:3000'
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password
      REDIS_URL: redis://redis:6379/1
    command: rails s -b "0.0.0.0" -e ${RAILS_ENV}

  sidekiq:
    build: .
    command: bundle exec sidekiq -e ${RAILS_ENV}
    depends_on:
      - postgres
      - redis
      - mossu
    volumes:
      - type: bind
        source: ./
        target: /opt/app/mossu
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password
      REDIS_URL: redis://redis:6379/1

volumes:
  mossu-postgres:
  mossu-redis: